### ISSUE TITLE
Flexible and extended configuration file

### ISSUE THREAD

**Issue by holgerw** [Cobliteam/cassandra-migrate#4]
I would like to suggest a more flexible yaml configuration.

1) Allow every property at the root level, as well as the profile level. Do not require any property at the root level, as long as it is provided at the profile level.

2) Allow the specification of user, password and host in the yaml file

Following is a sample yaml file, and its execution

```yaml
profiles:
  dev:
    keyspace: schema_dev
    host: localhost
    user: dev_user
    password: dev_pwd
  dev:
    keyspace: schema_prod
    host: db.my.dmain
    user: prod_user
migrations_path: .
replication:
  class: SimpleStrategy
  replication_factor: 3
```

```bash
cassandra-migrate migrate
cassandra-migrate --profile prod --password prod_pwd migrate
```

Thanks for cassandra-migrate.
