### ISSUE TITLE
NetworkTopologyStrategy In Config

### ISSUE THREAD

**Issue by omahoco** [Cobliteam/cassandra-migrate#40]
Hi,

Does your tool support schema creation using NetworkTopologyStrategy?

I've tried a config like:

```
profiles:
  prod:
    replication:
      class: NetworkTopologyStrategy
      dc1: 3
      dc2: 3
```

This config doesn't seem to work and the tool just fallback to SimpleStrategy with RF 1.
